wordpress:
  image: wordpress
  ports:
    - 8080:80
  volumes:
    - ./wordpress/wp_html:/var/www/html
  links:
    - mariadb:mysql
mariadb:
  image: mariadb
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: dbpass
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mariadb:mysql
  ports:
    - 8081:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: dbpass
    PMA_HOST: 127.0.0.1
